<?php
  $name = ["--Chọn nơi ở hiện tại--",
"Thành phố Hà Nội",
"Thành phố Hồ Chí Minh",
"Tỉnh An Giang",
"Tỉnh Bà Rịa - Vũng Tàu",
"Tỉnh Bạc Liêu",
"Tỉnh Bắc Giang",
"Tỉnh Bắc Kạn",
"Tỉnh Bắc Ninh",
"Tỉnh Bến Tre",
"Tỉnh Bình Dương",
"Tỉnh Bình Định",
"Tỉnh Bình Phước",
"Tỉnh Bình Thuận",
"Tỉnh Cao Bằng",
"Tỉnh Cà Mau",
"Thành phố Cần Thơ",
"Thành phố Hải Phòng",
"Thành phố Đà Nẵng",
"Tỉnh Gia Lai",
"Tỉnh Hòa Bình",
"Tỉnh Hà Giang",
"Tỉnh Hà Nam",
"Tỉnh Hà Tĩnh",
"Tỉnh Hưng Yên",
"Tỉnh Hải Dương",
"Tỉnh Hậu Giang",
"Tỉnh Điện Biên",
"Tỉnh Đắk Lắk",
"Tỉnh Đắk Nông",
"Tỉnh Đồng Nai",
"Tỉnh Đồng Tháp",
"Tỉnh Khánh Hòa",
"Tỉnh Kiên Giang",
"Tỉnh Kon Tum",
"Tỉnh Lai Châu",
"Tỉnh Long An",
"Tỉnh Lào Cai",
"Tỉnh Lâm Đồng",
"Tỉnh Lạng Sơn",
"Tỉnh Nam Định",
"Tỉnh Nghệ An",
"Tỉnh Ninh Bình",
"Tỉnh Ninh Thuận",
"Tỉnh Phú Thọ",
"Tỉnh Phú Yên",
"Tỉnh Quảng Bình",
"Tỉnh Quảng Nam",
"Tỉnh Quảng Ngãi",
"Tỉnh Quảng Ninh",
"Tỉnh Quảng Trị",
"Tỉnh Sóc Trăng",
"Tỉnh Sơn La",
"Tỉnh Thanh Hóa",
"Tỉnh Thái Bình",
"Tỉnh Thái Nguyên",
"Tỉnh Thừa Thiên - Huế",
"Tỉnh Tiền Giang",
"Tỉnh Trà Vinh",
"Tỉnh Tuyên Quang",
"Tỉnh Tây Ninh",
"Tỉnh Vĩnh Long",
"Tỉnh Vĩnh Phúc",
"Tỉnh Yên Bái"];
?>